version: '3.8'

services:
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5433:5432'

volumes:
    pgdata:
