openapi: 3.1.0
info:
  title: TGM - API
  description: Tibial global market
  version: 0.0.1
  contact:
    name: João Brasil
    email: joaovictor.brasil1992@gmail.com  
tags:
  - name: Items    
paths:
  /item:
    post:
      tags: 
        - Items
      description: Item create
      operationId: postItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                weight:
                  type: number
                levelRequired:
                  type: number
                vocation:
                  type: number
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    code:
                      type: integer
                    message:
                      type: string
                    error:
                      type: string

